/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTugasRouteImport } from './routes/_authenticated/tugas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLpdIndexRouteImport } from './routes/_authenticated/lpd.index'
import { Route as AuthenticatedLpdBaruRouteImport } from './routes/_authenticated/lpd.baru'
import { Route as AuthenticatedLpdIdRouteImport } from './routes/_authenticated/lpd.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTugasRoute = AuthenticatedTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLpdIndexRoute = AuthenticatedLpdIndexRouteImport.update({
  id: '/lpd/',
  path: '/lpd/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLpdBaruRoute = AuthenticatedLpdBaruRouteImport.update({
  id: '/lpd/baru',
  path: '/lpd/baru',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLpdIdRoute = AuthenticatedLpdIdRouteImport.update({
  id: '/lpd/$id',
  path: '/lpd/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/lpd/$id': typeof AuthenticatedLpdIdRoute
  '/lpd/baru': typeof AuthenticatedLpdBaruRoute
  '/lpd/': typeof AuthenticatedLpdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/lpd/$id': typeof AuthenticatedLpdIdRoute
  '/lpd/baru': typeof AuthenticatedLpdBaruRoute
  '/lpd': typeof AuthenticatedLpdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/tugas': typeof AuthenticatedTugasRoute
  '/_authenticated/lpd/$id': typeof AuthenticatedLpdIdRoute
  '/_authenticated/lpd/baru': typeof AuthenticatedLpdBaruRoute
  '/_authenticated/lpd/': typeof AuthenticatedLpdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/tugas'
    | '/lpd/$id'
    | '/lpd/baru'
    | '/lpd/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/tugas'
    | '/lpd/$id'
    | '/lpd/baru'
    | '/lpd'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/tugas'
    | '/_authenticated/lpd/$id'
    | '/_authenticated/lpd/baru'
    | '/_authenticated/lpd/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tugas': {
      id: '/_authenticated/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof AuthenticatedTugasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/': {
      id: '/_authenticated/lpd/'
      path: '/lpd'
      fullPath: '/lpd/'
      preLoaderRoute: typeof AuthenticatedLpdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/baru': {
      id: '/_authenticated/lpd/baru'
      path: '/lpd/baru'
      fullPath: '/lpd/baru'
      preLoaderRoute: typeof AuthenticatedLpdBaruRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/$id': {
      id: '/_authenticated/lpd/$id'
      path: '/lpd/$id'
      fullPath: '/lpd/$id'
      preLoaderRoute: typeof AuthenticatedLpdIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTugasRoute: typeof AuthenticatedTugasRoute
  AuthenticatedLpdIdRoute: typeof AuthenticatedLpdIdRoute
  AuthenticatedLpdBaruRoute: typeof AuthenticatedLpdBaruRoute
  AuthenticatedLpdIndexRoute: typeof AuthenticatedLpdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTugasRoute: AuthenticatedTugasRoute,
  AuthenticatedLpdIdRoute: AuthenticatedLpdIdRoute,
  AuthenticatedLpdBaruRoute: AuthenticatedLpdBaruRoute,
  AuthenticatedLpdIndexRoute: AuthenticatedLpdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
