/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTugasRouteImport } from './routes/_authenticated/tugas'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedNotifikasiRouteImport } from './routes/_authenticated/notifikasi'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master.index'
import { Route as AuthenticatedLpdIndexRouteImport } from './routes/_authenticated/lpd.index'
import { Route as PrintLpdIdRouteImport } from './routes/print.lpd.$id'
import { Route as PrintLaporanIdRouteImport } from './routes/print.laporan.$id'
import { Route as AuthenticatedMasterUserRouteImport } from './routes/_authenticated/master.user'
import { Route as AuthenticatedMasterTempatRouteImport } from './routes/_authenticated/master.tempat'
import { Route as AuthenticatedMasterRangkaRouteImport } from './routes/_authenticated/master.rangka'
import { Route as AuthenticatedMasterNomorSuratRouteImport } from './routes/_authenticated/master.nomor-surat'
import { Route as AuthenticatedMasterGolonganRouteImport } from './routes/_authenticated/master.golongan'
import { Route as AuthenticatedLpdBaruRouteImport } from './routes/_authenticated/lpd.baru'
import { Route as AuthenticatedLpdIdRouteImport } from './routes/_authenticated/lpd.$id'
import { Route as AuthenticatedLpdIdEditRouteImport } from './routes/_authenticated/lpd.$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTugasRoute = AuthenticatedTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotifikasiRoute = AuthenticatedNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/master/',
    path: '/master/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLpdIndexRoute = AuthenticatedLpdIndexRouteImport.update({
  id: '/lpd/',
  path: '/lpd/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PrintLpdIdRoute = PrintLpdIdRouteImport.update({
  id: '/print/lpd/$id',
  path: '/print/lpd/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintLaporanIdRoute = PrintLaporanIdRouteImport.update({
  id: '/print/laporan/$id',
  path: '/print/laporan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterUserRoute = AuthenticatedMasterUserRouteImport.update({
  id: '/master/user',
  path: '/master/user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterTempatRoute =
  AuthenticatedMasterTempatRouteImport.update({
    id: '/master/tempat',
    path: '/master/tempat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterRangkaRoute =
  AuthenticatedMasterRangkaRouteImport.update({
    id: '/master/rangka',
    path: '/master/rangka',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterNomorSuratRoute =
  AuthenticatedMasterNomorSuratRouteImport.update({
    id: '/master/nomor-surat',
    path: '/master/nomor-surat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterGolonganRoute =
  AuthenticatedMasterGolonganRouteImport.update({
    id: '/master/golongan',
    path: '/master/golongan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLpdBaruRoute = AuthenticatedLpdBaruRouteImport.update({
  id: '/lpd/baru',
  path: '/lpd/baru',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLpdIdRoute = AuthenticatedLpdIdRouteImport.update({
  id: '/lpd/$id',
  path: '/lpd/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLpdIdEditRoute = AuthenticatedLpdIdEditRouteImport.update({
  id: '/lpd/$id_/edit',
  path: '/lpd/$id/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/lpd/$id': typeof AuthenticatedLpdIdRoute
  '/lpd/baru': typeof AuthenticatedLpdBaruRoute
  '/master/golongan': typeof AuthenticatedMasterGolonganRoute
  '/master/nomor-surat': typeof AuthenticatedMasterNomorSuratRoute
  '/master/rangka': typeof AuthenticatedMasterRangkaRoute
  '/master/tempat': typeof AuthenticatedMasterTempatRoute
  '/master/user': typeof AuthenticatedMasterUserRoute
  '/print/laporan/$id': typeof PrintLaporanIdRoute
  '/print/lpd/$id': typeof PrintLpdIdRoute
  '/lpd/': typeof AuthenticatedLpdIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
  '/lpd/$id/edit': typeof AuthenticatedLpdIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tugas': typeof AuthenticatedTugasRoute
  '/lpd/$id': typeof AuthenticatedLpdIdRoute
  '/lpd/baru': typeof AuthenticatedLpdBaruRoute
  '/master/golongan': typeof AuthenticatedMasterGolonganRoute
  '/master/nomor-surat': typeof AuthenticatedMasterNomorSuratRoute
  '/master/rangka': typeof AuthenticatedMasterRangkaRoute
  '/master/tempat': typeof AuthenticatedMasterTempatRoute
  '/master/user': typeof AuthenticatedMasterUserRoute
  '/print/laporan/$id': typeof PrintLaporanIdRoute
  '/print/lpd/$id': typeof PrintLpdIdRoute
  '/lpd': typeof AuthenticatedLpdIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
  '/lpd/$id/edit': typeof AuthenticatedLpdIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tugas': typeof AuthenticatedTugasRoute
  '/_authenticated/lpd/$id': typeof AuthenticatedLpdIdRoute
  '/_authenticated/lpd/baru': typeof AuthenticatedLpdBaruRoute
  '/_authenticated/master/golongan': typeof AuthenticatedMasterGolonganRoute
  '/_authenticated/master/nomor-surat': typeof AuthenticatedMasterNomorSuratRoute
  '/_authenticated/master/rangka': typeof AuthenticatedMasterRangkaRoute
  '/_authenticated/master/tempat': typeof AuthenticatedMasterTempatRoute
  '/_authenticated/master/user': typeof AuthenticatedMasterUserRoute
  '/print/laporan/$id': typeof PrintLaporanIdRoute
  '/print/lpd/$id': typeof PrintLpdIdRoute
  '/_authenticated/lpd/': typeof AuthenticatedLpdIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
  '/_authenticated/lpd/$id_/edit': typeof AuthenticatedLpdIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notifikasi'
    | '/profil'
    | '/tugas'
    | '/lpd/$id'
    | '/lpd/baru'
    | '/master/golongan'
    | '/master/nomor-surat'
    | '/master/rangka'
    | '/master/tempat'
    | '/master/user'
    | '/print/laporan/$id'
    | '/print/lpd/$id'
    | '/lpd/'
    | '/master/'
    | '/lpd/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notifikasi'
    | '/profil'
    | '/tugas'
    | '/lpd/$id'
    | '/lpd/baru'
    | '/master/golongan'
    | '/master/nomor-surat'
    | '/master/rangka'
    | '/master/tempat'
    | '/master/user'
    | '/print/laporan/$id'
    | '/print/lpd/$id'
    | '/lpd'
    | '/master'
    | '/lpd/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifikasi'
    | '/_authenticated/profil'
    | '/_authenticated/tugas'
    | '/_authenticated/lpd/$id'
    | '/_authenticated/lpd/baru'
    | '/_authenticated/master/golongan'
    | '/_authenticated/master/nomor-surat'
    | '/_authenticated/master/rangka'
    | '/_authenticated/master/tempat'
    | '/_authenticated/master/user'
    | '/print/laporan/$id'
    | '/print/lpd/$id'
    | '/_authenticated/lpd/'
    | '/_authenticated/master/'
    | '/_authenticated/lpd/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrintLaporanIdRoute: typeof PrintLaporanIdRoute
  PrintLpdIdRoute: typeof PrintLpdIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tugas': {
      id: '/_authenticated/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof AuthenticatedTugasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifikasi': {
      id: '/_authenticated/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AuthenticatedNotifikasiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/': {
      id: '/_authenticated/lpd/'
      path: '/lpd'
      fullPath: '/lpd/'
      preLoaderRoute: typeof AuthenticatedLpdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/print/lpd/$id': {
      id: '/print/lpd/$id'
      path: '/print/lpd/$id'
      fullPath: '/print/lpd/$id'
      preLoaderRoute: typeof PrintLpdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/laporan/$id': {
      id: '/print/laporan/$id'
      path: '/print/laporan/$id'
      fullPath: '/print/laporan/$id'
      preLoaderRoute: typeof PrintLaporanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/master/user': {
      id: '/_authenticated/master/user'
      path: '/master/user'
      fullPath: '/master/user'
      preLoaderRoute: typeof AuthenticatedMasterUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/tempat': {
      id: '/_authenticated/master/tempat'
      path: '/master/tempat'
      fullPath: '/master/tempat'
      preLoaderRoute: typeof AuthenticatedMasterTempatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/rangka': {
      id: '/_authenticated/master/rangka'
      path: '/master/rangka'
      fullPath: '/master/rangka'
      preLoaderRoute: typeof AuthenticatedMasterRangkaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/nomor-surat': {
      id: '/_authenticated/master/nomor-surat'
      path: '/master/nomor-surat'
      fullPath: '/master/nomor-surat'
      preLoaderRoute: typeof AuthenticatedMasterNomorSuratRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/golongan': {
      id: '/_authenticated/master/golongan'
      path: '/master/golongan'
      fullPath: '/master/golongan'
      preLoaderRoute: typeof AuthenticatedMasterGolonganRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/baru': {
      id: '/_authenticated/lpd/baru'
      path: '/lpd/baru'
      fullPath: '/lpd/baru'
      preLoaderRoute: typeof AuthenticatedLpdBaruRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/$id': {
      id: '/_authenticated/lpd/$id'
      path: '/lpd/$id'
      fullPath: '/lpd/$id'
      preLoaderRoute: typeof AuthenticatedLpdIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lpd/$id_/edit': {
      id: '/_authenticated/lpd/$id_/edit'
      path: '/lpd/$id/edit'
      fullPath: '/lpd/$id/edit'
      preLoaderRoute: typeof AuthenticatedLpdIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotifikasiRoute: typeof AuthenticatedNotifikasiRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTugasRoute: typeof AuthenticatedTugasRoute
  AuthenticatedLpdIdRoute: typeof AuthenticatedLpdIdRoute
  AuthenticatedLpdBaruRoute: typeof AuthenticatedLpdBaruRoute
  AuthenticatedMasterGolonganRoute: typeof AuthenticatedMasterGolonganRoute
  AuthenticatedMasterNomorSuratRoute: typeof AuthenticatedMasterNomorSuratRoute
  AuthenticatedMasterRangkaRoute: typeof AuthenticatedMasterRangkaRoute
  AuthenticatedMasterTempatRoute: typeof AuthenticatedMasterTempatRoute
  AuthenticatedMasterUserRoute: typeof AuthenticatedMasterUserRoute
  AuthenticatedLpdIndexRoute: typeof AuthenticatedLpdIndexRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
  AuthenticatedLpdIdEditRoute: typeof AuthenticatedLpdIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotifikasiRoute: AuthenticatedNotifikasiRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTugasRoute: AuthenticatedTugasRoute,
  AuthenticatedLpdIdRoute: AuthenticatedLpdIdRoute,
  AuthenticatedLpdBaruRoute: AuthenticatedLpdBaruRoute,
  AuthenticatedMasterGolonganRoute: AuthenticatedMasterGolonganRoute,
  AuthenticatedMasterNomorSuratRoute: AuthenticatedMasterNomorSuratRoute,
  AuthenticatedMasterRangkaRoute: AuthenticatedMasterRangkaRoute,
  AuthenticatedMasterTempatRoute: AuthenticatedMasterTempatRoute,
  AuthenticatedMasterUserRoute: AuthenticatedMasterUserRoute,
  AuthenticatedLpdIndexRoute: AuthenticatedLpdIndexRoute,
  AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
  AuthenticatedLpdIdEditRoute: AuthenticatedLpdIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrintLaporanIdRoute: PrintLaporanIdRoute,
  PrintLpdIdRoute: PrintLpdIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
