// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest, getRequestHeader, setResponseHeader, setResponseHeaders } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { parseCookie, stringifySetCookie } from 'cookie'
import type { Database } from './types'

function isHttpsRequest(request: Request) {
  const proto = request.headers.get('x-forwarded-proto')
  if (proto) return proto.includes('https')
  return new URL(request.url).protocol === 'https:'
}

function createUserScopedClient(url: string, key: string, token: string) {
  return createClient<Database>(url, key, {
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  })
}

function supabasePublishableFetch(key: string) {
  return (input: RequestInfo | URL, init?: RequestInit) => {
    const headers = new Headers(init?.headers)
    if (key.startsWith('sb_') && headers.get('Authorization') === `Bearer ${key}`) {
      headers.delete('Authorization')
    }
    headers.set('apikey', key)
    return fetch(input, { ...init, headers })
  }
}

function getSupabaseEnv() {
  const viteEnv = import.meta.env as Record<string, string | undefined>;
  const SUPABASE_URL = process.env.SUPABASE_URL ?? viteEnv.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    process.env.SUPABASE_PUBLISHABLE_KEY ?? viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY;

  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

function createRequestCookieAdapter(request: Request) {
  const cookieHeader = getRequestHeader('cookie') ?? request.headers.get('cookie') ?? '';
  const cookieMap = new Map(
    Object.entries(parseCookie(cookieHeader)).filter(
      (entry): entry is [string, string] => typeof entry[1] === 'string',
    ),
  );

  return {
    names: () => [...cookieMap.keys()].filter((name) => name.startsWith('sb-')),
    headerLength: () => cookieHeader.length,
    getAll() {
      return [...cookieMap.entries()].map(([name, value]) => ({ name, value }));
    },
    setAll(
      cookiesToSet: { name: string; value: string; options: CookieOptions }[],
      headers: Record<string, string>,
    ) {
      setResponseHeaders(headers);
      setResponseHeader(
        'Set-Cookie',
        cookiesToSet.map(({ name, value, options }) =>
          stringifySetCookie({ name, value, path: '/', ...options }),
        ),
      );

      cookiesToSet.forEach(({ name, value, options }) => {
        if (value === '' || options.maxAge === 0) {
          cookieMap.delete(name);
        } else {
          cookieMap.set(name, value);
        }
      });
    },
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = getSupabaseEnv();

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    let token = authHeader?.startsWith('Bearer ') ? authHeader.replace('Bearer ', '') : '';
    const requestCookies = createRequestCookieAdapter(request);
    const supabaseCookieNames = requestCookies.names();

    if (authHeader && !authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    if (!token) {
      const supabaseFromCookies = createServerClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          cookieOptions: {
            path: '/',
            sameSite: 'lax',
            secure: isHttpsRequest(request),
          },
          cookies: {
            getAll: requestCookies.getAll,
            setAll: requestCookies.setAll,
          },
          global: {
            fetch: supabasePublishableFetch(SUPABASE_PUBLISHABLE_KEY!),
          },
        },
      );

      // Use getUser() — more tolerant of publishable-key formats than getClaims()
      // and reflects the real auth-server verdict.
      const { data: userData, error: userError } = await supabaseFromCookies.auth.getUser();
      if (userError || !userData?.user) {
        console.warn('[auth-mw] cookie-getUser failed', {
          message: userError?.message,
          status: (userError as { status?: number } | null)?.status,
          cookieHeaderLen: requestCookies.headerLength(),
          hadSupabaseCookies: supabaseCookieNames.length > 0,
        });
        throw new Error(
          supabaseCookieNames.length === 0
            ? 'Unauthorized: No authorization header or auth cookie'
            : `Unauthorized: cookie session invalid (${userError?.message ?? 'unknown'})`,
        );
      }

      const { data: cookieSession } = await supabaseFromCookies.auth.getSession();
      token = cookieSession.session?.access_token ?? '';
      if (!token) {
        throw new Error('Unauthorized: cookie session had no access_token');
      }
    }

    const supabase = createUserScopedClient(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, token);

    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      console.warn('[auth-mw] getUser failed', { message: error?.message });
      throw new Error(`Unauthorized: Invalid token (${error?.message ?? 'no user'})`);
    }

    if (!data.user.id) {
      throw new Error('Unauthorized: No user ID found in token');
    }


    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: { sub: data.user.id },
      },
    });
  },
);
