// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest, setResponseHeader, setResponseHeaders } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import { createServerClient } from '@supabase/ssr'
import { parseCookie, stringifySetCookie } from 'cookie'
import type { Database } from './types'

function isHttpsRequest(request: Request) {
  const proto = request.headers.get('x-forwarded-proto')
  if (proto) return proto.includes('https')
  return new URL(request.url).protocol === 'https:'
}

function createUserScopedClient(url: string, key: string, token: string) {
  return createClient<Database>(url, key, {
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  })
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    let token = authHeader?.startsWith('Bearer ') ? authHeader.replace('Bearer ', '') : '';

    if (authHeader && !authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    if (!token) {
      const parsedCookies = parseCookie(request.headers.get('cookie') ?? '');
      const supabaseFromCookies = createServerClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          cookieOptions: {
            path: '/',
            sameSite: 'lax',
            secure: isHttpsRequest(request),
          },
          cookies: {
            getAll() {
              return Object.entries(parsedCookies)
                .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
                .map(([name, value]) => ({ name, value }));
            },
            setAll(cookiesToSet, headers) {
              setResponseHeaders(headers);
              setResponseHeader(
                'Set-Cookie',
                cookiesToSet.map(({ name, value, options }) =>
                  stringifySetCookie({ name, value, ...options }),
                ),
              );
            },
          },
        },
      );

      const { data: cookieClaims, error: cookieClaimsError } = await supabaseFromCookies.auth.getClaims();
      if (cookieClaimsError || !cookieClaims?.claims?.sub) {
        throw new Error('Unauthorized: No authorization header provided');
      }

      const { data: cookieSession } = await supabaseFromCookies.auth.getSession();
      token = cookieSession.session?.access_token ?? '';
    }

    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createUserScopedClient(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, token);

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
