// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest, setResponseHeader, setResponseHeaders } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import { createServerClient } from '@supabase/ssr'
import { parseCookie, stringifySetCookie } from 'cookie'
import type { Database } from './types'

function isHttpsRequest(request: Request) {
  const proto = request.headers.get('x-forwarded-proto')
  if (proto) return proto.includes('https')
  return new URL(request.url).protocol === 'https:'
}

function createUserScopedClient(url: string, key: string, token: string) {
  return createClient<Database>(url, key, {
    global: {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  })
}

function supabasePublishableFetch(key: string) {
  return (input: RequestInfo | URL, init?: RequestInit) => {
    const headers = new Headers(init?.headers)
    if (key.startsWith('sb_') && headers.get('Authorization') === `Bearer ${key}`) {
      headers.delete('Authorization')
    }
    headers.set('apikey', key)
    return fetch(input, { ...init, headers })
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    const cookieHeader = request.headers.get('cookie') ?? '';
    let token = authHeader?.startsWith('Bearer ') ? authHeader.replace('Bearer ', '') : '';

    const parsedCookies = parseCookie(cookieHeader);
    const supabaseCookieNames = Object.keys(parsedCookies).filter((n) => n.startsWith('sb-'));

    // Diagnostic (temporary): reveal what actually arrives at the Worker.
    console.log('[auth-mw] diag', {
      hasAuthHeader: !!authHeader,
      authHeaderScheme: authHeader?.split(' ')[0],
      cookieHeaderLen: cookieHeader.length,
      supabaseCookieNames,
      url: request.url,
    });

    if (authHeader && !authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    if (!token) {
      const supabaseFromCookies = createServerClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          cookieOptions: {
            path: '/',
            sameSite: 'lax',
            secure: isHttpsRequest(request),
          },
          cookies: {
            getAll() {
              return Object.entries(parsedCookies)
                .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
                .map(([name, value]) => ({ name, value }));
            },
            setAll(cookiesToSet, headers) {
              setResponseHeaders(headers);
              setResponseHeader(
                'Set-Cookie',
                cookiesToSet.map(({ name, value, options }) =>
                  stringifySetCookie({ name, value, ...options }),
                ),
              );
            },
          },
          global: {
            fetch: supabasePublishableFetch(SUPABASE_PUBLISHABLE_KEY!),
          },
        },
      );

      // Use getUser() — more tolerant of publishable-key formats than getClaims()
      // and reflects the real auth-server verdict.
      const { data: userData, error: userError } = await supabaseFromCookies.auth.getUser();
      if (userError || !userData?.user) {
        console.log('[auth-mw] cookie-getUser failed', {
          message: userError?.message,
          status: (userError as { status?: number } | null)?.status,
          hadSupabaseCookies: supabaseCookieNames.length > 0,
        });
        throw new Error(
          supabaseCookieNames.length === 0
            ? 'Unauthorized: No authorization header or auth cookie'
            : `Unauthorized: cookie session invalid (${userError?.message ?? 'unknown'})`,
        );
      }

      const { data: cookieSession } = await supabaseFromCookies.auth.getSession();
      token = cookieSession.session?.access_token ?? '';
      if (!token) {
        throw new Error('Unauthorized: cookie session had no access_token');
      }
    }

    const supabase = createUserScopedClient(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, token);

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      console.log('[auth-mw] getClaims failed', { message: error?.message });
      throw new Error(`Unauthorized: Invalid token (${error?.message ?? 'no claims'})`);
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }


    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
