// This file is automatically generated. Do not edit it directly.
import { createBrowserClient, type CookieOptions } from '@supabase/ssr';
import type { SupabaseClient } from '@supabase/supabase-js';
import { parseCookie, stringifySetCookie } from 'cookie';
import type { Database } from './types';

function getStorageKey(supabaseUrl: string) {
  return `sb-${new URL(supabaseUrl).hostname.split('.')[0]}-auth-token`;
}

function getBrowserCookiesWithLegacySession(storageKey: string) {
  const parsed = parseCookie(document.cookie);
  const cookies = Object.entries(parsed)
    .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
    .map(([name, value]) => ({ name, value }));

  const hasCookieSession = cookies.some(
    ({ name }) => name === storageKey || name.startsWith(`${storageKey}.`),
  );
  const legacySession = window.localStorage.getItem(storageKey);

  if (!hasCookieSession && legacySession) {
    cookies.push({ name: storageKey, value: legacySession });
  }

  return cookies;
}

async function getServerRequestCookies() {
  try {
    const { getRequestHeader } = await import('@tanstack/react-start/server');
    const cookieHeader = getRequestHeader('cookie') ?? '';
    return Object.entries(parseCookie(cookieHeader))
      .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
      .map(([name, value]) => ({ name, value }));
  } catch {
    return [];
  }
}

async function setServerResponseCookies(
  cookiesToSet: { name: string; value: string; options: CookieOptions }[],
  headers: Record<string, string>,
) {
  try {
    const { setResponseHeader, setResponseHeaders } = await import('@tanstack/react-start/server');
    setResponseHeaders(headers);
    setResponseHeader(
      'Set-Cookie',
      cookiesToSet.map(({ name, value, options }) =>
        stringifySetCookie({ name, value, path: '/', ...options }),
      ),
    );
  } catch {
    // No active server request context; leave cookies untouched.
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const serverEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || serverEnv?.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || serverEnv?.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const storageKey = getStorageKey(SUPABASE_URL);

  const client = createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    cookieOptions: {
      path: '/',
      sameSite: 'lax',
      secure: typeof window === 'undefined' ? true : window.location.protocol === 'https:',
    },
    cookies: {
      getAll() {
        if (typeof window === 'undefined') {
          return getServerRequestCookies();
        }
        return getBrowserCookiesWithLegacySession(storageKey);
      },
      setAll(cookiesToSet, headers) {
        if (typeof window === 'undefined') {
          return setServerResponseCookies(cookiesToSet, headers);
        }

        const touchesAuthCookie = cookiesToSet.some(
          ({ name }) => name === storageKey || name.startsWith(`${storageKey}.`),
        );
        cookiesToSet.forEach(({ name, value, options }) => {
          document.cookie = stringifySetCookie({ name, value, path: '/', ...options });
        });
        if (touchesAuthCookie) {
          window.localStorage.removeItem(storageKey);
        }
      },
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  });

  if (typeof window !== 'undefined' && window.localStorage.getItem(storageKey)) {
    queueMicrotask(() => {
      client.auth
        .getSession()
        .then(({ data }) => {
          if (data.session?.access_token && data.session.refresh_token) {
            return client.auth.setSession({
              access_token: data.session.access_token,
              refresh_token: data.session.refresh_token,
            });
          }
        })
        .catch(() => {
          // If the legacy cache is invalid, keep the normal auth flow in charge.
        });
    });
  }

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

